#ifndef QRENCODER_CONFIG_H
#define QRENCODER_CONFIG_H

#define STATIC_IN_RELEASE static
#define MAJOR_VERSION 4
#define MINOR_VERSION 1
#define MICRO_VERSION 0
#define VERSION "1.0"

#endif/*QRENCODER_CONFIG_H*/
