#!/usr/bin/env python
# -*- coding: utf-8 -*-

import types
from config_compoents import compoents_config


can_stack_libs = []

if get_config_val(compoents_config, 'EN_AW_CAN_STACK', False) is True:
    # canopen
    if get_config_val(compoents_config, 'EN_AW_CANOPEN_MST', False) is True or get_config_val(compoents_config, 'EN_AW_CANOPEN_SLV', False) is True:
        SConscript_and_add_return_library('CANopen_adapter/SConscript', can_stack_libs)
        
    # CanFestival-3.8
    if get_config_val(compoents_config, 'EN_AW_CANFESTIVAL_3_8', False) is True:
        SConscript_and_add_return_library('CanFestival-3.8_adapter/SConscript', can_stack_libs)
        
    # CanFestival-3.0-rc3
    elif get_config_val(compoents_config, 'EN_AW_CANFESTIVAL_3_0', False) is True:
        SConscript_and_add_return_library('CanFestival-3.0-rc3_adapter/SConscript', can_stack_libs)

if 0 == len(can_stack_libs):
    can_stack_libs = None
Return('can_stack_libs')
