
/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

/**************************************************************************/
/* Declaration of the mapped variables                                    */
/**************************************************************************/

/**************************************************************************/
/* Declaration of the value range types                                   */
/**************************************************************************/

UNS32 aworkstest_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 aworkstest_bDeviceNodeId = 0x01;

/**************************************************************************/
/* Array of message processing information */

const UNS8 aworkstest_iam_a_slave = 0;

TIMER_HANDLE aworkstest_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 aworkstest_obj1000 = 0x12D;	/* 301 */
                    subindex aworkstest_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&aworkstest_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 aworkstest_obj1001 = 0x0;	/* 0 */
                    subindex aworkstest_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_obj1001 }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 aworkstest_obj1005 = 0x0;	/* 0 */
                    ODCallback_t aworkstest_Index1005_callbacks[] =
                     {
                       NULL,
                     };
                    subindex aworkstest_Index1005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 aworkstest_obj1006 = 0x0;   /* 0 */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 aworkstest_highestSubIndex_obj1016 = 0;
                    UNS32 aworkstest_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 aworkstest_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 aworkstest_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 aworkstest_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 aworkstest_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 aworkstest_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex aworkstest_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&aworkstest_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&aworkstest_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&aworkstest_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&aworkstest_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 aworkstest_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 aworkstest_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS32 aworkstest_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex aworkstest_Index1280[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 aworkstest_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1400_COB_ID_used_by_PDO = 0x201;    /* 385 */
                    UNS8 aworkstest_obj1400_Transmission_Type = 0x1;    /* 1 */
                    UNS16 aworkstest_obj1400_Inhibit_Time = 0x0;    /* 0 */
                    UNS16 aworkstest_obj1400_Compatibility_Entry = 0x0; /* 0 */
                    UNS16 aworkstest_obj1400_Event_Timer = 0x0; /* 0 */
                    subindex aworkstest_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1400_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 aworkstest_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1401_COB_ID_used_by_PDO = 0x301;    /* 641 */
                    UNS8 aworkstest_obj1401_Transmission_Type = 0x1;    /* 1 */
                    UNS16 aworkstest_obj1401_Inhibit_Time = 0x0;    /* 0 */
                    UNS16 aworkstest_obj1401_Compatibility_Entry = 0x0; /* 0 */
                    UNS16 aworkstest_obj1401_Event_Timer = 0x0; /* 0 */
                    subindex aworkstest_Index1401[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1401_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1401_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 aworkstest_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1600[] =
                    {
                      0x20000020,   /* 536870920 */
                      0x20010020    /* 536936456 */
                    };
                    subindex aworkstest_Index1600[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 aworkstest_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1601[] =
                    {
                      0x20020008,   /* 537001992 */
                      0x20030008    /* 537067528 */
                    };
                    subindex aworkstest_Index1601[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1601[1] }
                     };


/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 aworkstest_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1800_COB_ID_used_by_PDO = 0x182; /* 386 */
                    UNS8 aworkstest_obj1800_Transmission_Type = TRANS_EVENT; /* 0 */
                    UNS16 aworkstest_obj1800_Inhibit_Time = 0x0; /* 0 */
                    UNS16 aworkstest_obj1800_Compatibility_Entry = 0x0;  /* 0 */
                    UNS16 aworkstest_obj1800_Event_Timer = 0x0;  /* 0 */
                    subindex aworkstest_Index1800[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1800_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 aworkstest_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1801_COB_ID_used_by_PDO = 0x282; /* 642 */
                    UNS8 aworkstest_obj1801_Transmission_Type = 0x0; /* 0 */
                    UNS16 aworkstest_obj1801_Inhibit_Time = 0x0; /* 0 */
                    UNS16 aworkstest_obj1801_Compatibility_Entry = 0x0;  /* 0 */
                    UNS16 aworkstest_obj1801_Event_Timer = 0x0;  /* 0 */
                    subindex aworkstest_Index1801[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1801_Inhibit_Time },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&aworkstest_obj1801_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 aworkstest_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1A00[] =
                    {
                      0x20040020,   /* 536870920 */
                      0x20050020    /* 536936456 */
                    };
                    subindex aworkstest_Index1A00[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 aworkstest_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 aworkstest_obj1A01[] =
                    {
                      0x20060008,   /* 537001992 */
                      0x20070008    /* 537067528 */
                    };
                    subindex aworkstest_Index1A01[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_obj1A01[1] }
                     };

/* index 0x2000 :   Mapped variable aworkstest_RecvMap1 */
                    UNS32 aworkstest_RecvMap1 = 0x0;      /* Mapped at index 0x2000, subindex 0x00 */
                    ODCallback_t aworkstest_RecvMap1_callbacks[] =
                     {
                       NULL,
                     };
                    subindex aworkstest_Index2000[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_RecvMap1 }
                     };

/* index 0x2001 :   Mapped variable aworkstest_RecvMap2 */
                    UNS32 aworkstest_RecvMap2 = 0x0;      /* Mapped at index 0x2001, subindex 0x00 */
                    subindex aworkstest_Index2001[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_RecvMap2 }
                     };

/* index 0x2002 :   Mapped variable aworkstest_RecvMap3 */
                    UNS8 aworkstest_RecvMap3 = 0x0;      /* Mapped at index 0x2002, subindex 0x00 */
                    subindex aworkstest_Index2002[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_RecvMap3 }
                     };

/* index 0x2003 :   Mapped variable aworkstest_RecvMap4 */
                    UNS8 aworkstest_RecvMap4 = 0x0;      /* Mapped at index 0x2003, subindex 0x00 */
                    subindex aworkstest_Index2003[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_RecvMap4 }
                     };

/* index 0x2004 :   Mapped variable aworkstest_SendMap1 */
                    UNS32 aworkstest_SendMap1 = 0x0;      /* Mapped at index 0x2000, subindex 0x00 */
                    ODCallback_t aworkstest_SendMap1_callbacks[] =
                     {
                       NULL,
                     };
                    subindex aworkstest_Index2004[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_SendMap1 }
                     };

/* index 0x2005 :   Mapped variable aworkstest_SendMap2 */
                    UNS32 aworkstest_SendMap2 = 0x0;      /* Mapped at index 0x2001, subindex 0x00 */
                    subindex aworkstest_Index2005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&aworkstest_SendMap2 }
                     };

/* index 0x2006 :   Mapped variable aworkstest_SendMap3 */
                    UNS8 aworkstest_SendMap3 = 0x0;      /* Mapped at index 0x2002, subindex 0x00 */
                    subindex aworkstest_Index2006[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_SendMap3 }
                     };

/* index 0x2007 :   Mapped variable aworkstest_SendMap4 */
                    UNS8 aworkstest_SendMap4 = 0x0;      /* Mapped at index 0x2003, subindex 0x00 */
                    subindex aworkstest_Index2007[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&aworkstest_SendMap4 }
                     };

const indextable aworkstest_objdict[] =
{
  { (subindex*)aworkstest_Index1000,sizeof(aworkstest_Index1000)/sizeof(aworkstest_Index1000[0]), 0x1000},
  { (subindex*)aworkstest_Index1001,sizeof(aworkstest_Index1001)/sizeof(aworkstest_Index1001[0]), 0x1001},
  { (subindex*)aworkstest_Index1005,sizeof(aworkstest_Index1005)/sizeof(aworkstest_Index1005[0]), 0x1005},
  { (subindex*)aworkstest_Index1018,sizeof(aworkstest_Index1018)/sizeof(aworkstest_Index1018[0]), 0x1018},
  { (subindex*)aworkstest_Index1280,sizeof(aworkstest_Index1280)/sizeof(aworkstest_Index1280[0]), 0x1280},
  { (subindex*)aworkstest_Index1400,sizeof(aworkstest_Index1400)/sizeof(aworkstest_Index1400[0]), 0x1400},
  { (subindex*)aworkstest_Index1401,sizeof(aworkstest_Index1401)/sizeof(aworkstest_Index1401[0]), 0x1401},
  { (subindex*)aworkstest_Index1600,sizeof(aworkstest_Index1600)/sizeof(aworkstest_Index1600[0]), 0x1600},
  { (subindex*)aworkstest_Index1601,sizeof(aworkstest_Index1601)/sizeof(aworkstest_Index1601[0]), 0x1601},
  { (subindex*)aworkstest_Index1800,sizeof(aworkstest_Index1800)/sizeof(aworkstest_Index1800[0]), 0x1800},
  { (subindex*)aworkstest_Index1801,sizeof(aworkstest_Index1801)/sizeof(aworkstest_Index1801[0]), 0x1801},
  { (subindex*)aworkstest_Index1A00,sizeof(aworkstest_Index1A00)/sizeof(aworkstest_Index1A00[0]), 0x1A00},
  { (subindex*)aworkstest_Index1A01,sizeof(aworkstest_Index1A01)/sizeof(aworkstest_Index1A01[0]), 0x1A01},
  { (subindex*)aworkstest_Index2000,sizeof(aworkstest_Index2000)/sizeof(aworkstest_Index2000[0]), 0x2000},
  { (subindex*)aworkstest_Index2001,sizeof(aworkstest_Index2001)/sizeof(aworkstest_Index2001[0]), 0x2001},
  { (subindex*)aworkstest_Index2002,sizeof(aworkstest_Index2002)/sizeof(aworkstest_Index2002[0]), 0x2002},
  { (subindex*)aworkstest_Index2003,sizeof(aworkstest_Index2003)/sizeof(aworkstest_Index2003[0]), 0x2003},
  { (subindex*)aworkstest_Index2004,sizeof(aworkstest_Index2004)/sizeof(aworkstest_Index2004[0]), 0x2004},
  { (subindex*)aworkstest_Index2005,sizeof(aworkstest_Index2005)/sizeof(aworkstest_Index2005[0]), 0x2005},
  { (subindex*)aworkstest_Index2006,sizeof(aworkstest_Index2006)/sizeof(aworkstest_Index2006[0]), 0x2006},
  { (subindex*)aworkstest_Index2007,sizeof(aworkstest_Index2007)/sizeof(aworkstest_Index2007[0]), 0x2007},
};

const indextable * aworkstest_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = aworkstest_Index1005_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1280: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1401: i = 6;break;
		case 0x1600: i = 7;break;
		case 0x1601: i = 8;break;
		case 0x1800: i = 9;break;
		case 0x1801: i = 10;break;
		case 0x1A00: i = 11;break;
		case 0x1A01: i = 12;break;
		case 0x2000: i = 13;*callbacks = aworkstest_RecvMap1_callbacks; break;
		case 0x2001: i = 14;break;
		case 0x2002: i = 15;break;
		case 0x2003: i = 16;break;
		case 0x2004: i = 17;*callbacks = aworkstest_SendMap1_callbacks; break;
		case 0x2005: i = 18;break;
		case 0x2006: i = 19;break;
		case 0x2007: i = 20;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &aworkstest_objdict[i];
}

/* To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
UNS8 aworkstest_count_sync[1] = {0,};

quick_index aworkstest_firstIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  5, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  9, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

quick_index aworkstest_lastIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  6, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

UNS16 aworkstest_ObjdictSize = sizeof(aworkstest_objdict)/sizeof(aworkstest_objdict[0]);

CO_Data aworkstest_Data = CANOPEN_NODE_DATA_INITIALIZER(aworkstest);

