#!/usr/bin/env python
# -*- coding: utf-8 -*-

from config_build_common import build_common_config
from config_aw_base import aw_base_config
from config_lwip import aw_lwip_config
import os


cur_build_path = Dir('.', False)
org_build_path = str(cur_build_path.srcnode())

NAME = 'firmware_cyw43438'

FIRMWARE_VERSION = '7.0.0.3'

INSTALL_PATH = build_common_config.AW_SDK_INSTALL_PATH + 'resources/firmware/cyw43438'

INSTALL_CONTENT = Glob(org_build_path + '/*.h')
INSTALL_CONTENT.append(Glob(org_build_path + '/*.txt'))

SOURCE = []

if build_common_config.AW_COMPILER_TOOLS == 'armcc':
    SOURCE.append(FIRMWARE_VERSION + '/firmware_cyw43438_apsta_armcc.S')
else:
    SOURCE.append(FIRMWARE_VERSION + '/firmware_cyw43438_apsta_gcc.S')

INCLUDE = list()
INCLUDE.append(FIRMWARE_VERSION)
    
    
lib_file = Library(NAME, SOURCE, CPPPATH = INCLUDE)


Return('lib_file')
